dist: trusty
sudo: required
language: cpp
os: linux
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

script:
  - export CODECOV_TOKEN="964ca3de-67f4-4065-a81a-b86c489c1738"
  - bash <(curl -s https://codecov.io/bash)
  - git clone https://github.com/jbeder/yaml-cpp.git --depth=1
  - mkdir -p yaml-cpp/build && cd yaml-cpp/build && cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON .. && make -j8
  - cd ../..
  - cp -rf yaml-cpp/include dependencies/yaml-cpp/
  - cp -rf yaml-cpp/build/libyaml-cpp.a dependencies/yaml-cpp/lib/
  - git clone https://github.com/google/googletest.git --depth=1
  - mkdir -p googletest/build && cd googletest/build && cmake -DCMAKE_POSITION_INDEPENDENT_CODE=ON .. && make -j8
  - cd ../..
  - cp -rf googletest/googletest/include dependencies/googletest/
  - cp -rf googletest/build/lib/* dependencies/googletest/lib/
  - export CC=gcc-7
  - export CXX=g++-7
  - gcc -v && g++ -v && cmake --version
  - rm -rf build
  - mkdir build && cd build
  - cmake ..
  - make
