dist: trusty
sudo: required
language: cpp
os: linux
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake
      - libstdc++6

script:
  - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  - export LINKER_FLAGS="-stdlib=libc++ -lc++abi"
  - gcc -v && g++ -v && cmake --version

install:
  - mkdir build && cd build
  - cmake -DCMAKE_EXE_LINKER_FLAGS=${LINKER_FLAGS} ..
  - make