dist: trusty
sudo: required
language: cpp
os: linux
compiler: gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

script:
  - export CODECOV_TOKEN="964ca3de-67f4-4065-a81a-b86c489c1738"
  - bash <(curl -s https://codecov.io/bash)
  - export CC=gcc-7
  - export CXX=g++-7
  - gcc -v && g++ -v && cmake --version
  - rm -rf build
  - cmake -S . -B build
  - cmake --build build
