api: ctp
trade_server_address: tcp://180.168.146.187:10130
quote_server_address: tcp://180.168.146.187:10131
broker_id: 9999
investor_id: 123456
password: abc123456
auth_code: 0000000000000000
app_id: simnow_client_test
subscription_list: [rb2009, rb2007]

throttle_rate_limit_period_ms: 1000
throttle_rate_order_limit: 2
throttle_rate_volume_limit: 100
