api: xtp
trade_server_address: tcp://111.111.222.222:12345
quote_server_address: tcp://111.111.222.222:12346
investor_id: 88888888888
password: 1234567
auth_code: 22222222222222222222222222222aa
subscription_list: 
  - 600036
  - 600001

throttle_rate_limit_period_ms: 1000
throttle_rate_order_limit: 20
throttle_rate_volume_limit: 0

arg0: ../config/etf_list.csv         # etf清单文件，用于etf套利
arg1: ../config/etf_components.csv   # etf成分股文件，用于etf套利
